name       : cryptopp
version    : '7.0'
release    : 6
source     :
    - https://github.com/weidai11/cryptopp/archive/CRYPTOPP_7_0_0.tar.gz : 3ee97903882b5f58c88b6f9d2ce50fd1000be95479180c7b4681cd3f4c1c7629
license    : BSL-1.0
component  : programming
summary    : Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
description: |
    Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
build      : |
    make libcryptopp.pc
    %make dynamic
install    : |
    %make_install PREFIX=/usr
