name       : cryptopp
version    : '8.2'
release    : 7
source     :
    - https://github.com/weidai11/cryptopp/archive/CRYPTOPP_8_2_0.tar.gz : e3bcd48a62739ad179ad8064b523346abb53767bcbefc01fe37303412292343e
license    : BSL-1.0
component  : programming
summary    : Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
description: |
    Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
build      : |
    %make dynamic libcryptopp.pc
install    : |
    %make_install PREFIX=/usr

    # Remove unused test data
    rm -rf $installdir/usr/share $installdir/usr/bin
