name       : cryptopp
version    : 5.6.4
release    : 4
source     :
    - http://netix.dl.sourceforge.net/project/cryptopp/cryptopp/5.6.4/cryptopp564.zip : be430377b05c15971d5ccb6e44b4d95470f561024ed6d701fe3da3a188c84ad7
license    : BSL-1.0
component  : programming
summary    : Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
description: |
    Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-butchering-flags.patch
    %patch -p1 < $pkgfiles/security/cve-2017-9434.patch
build      : |
    %make dynamic
install    : |
    %make_install PREFIX=/usr
