name       : cryptopp
version    : 5.6.5
release    : 5
source     :
    - https://www.cryptopp.com/cryptopp565.zip : a75ef486fe3128008bbb201efee3dcdcffbe791120952910883b26337ec32c34
license    : BSL-1.0
component  : programming
summary    : Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
description: |
    Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
setup      : |
    %patch -p1 < $pkgfiles/0001-Stop-butchering-flags.patch
    %patch -p1 < $pkgfiles/security/cve-2017-9434.patch
build      : |
    %make dynamic
install    : |
    %make_install PREFIX=/usr
