name       : cryptopp
version    : '8.6'
release    : 8
source     :
    - https://github.com/weidai11/cryptopp/archive/refs/tags/CRYPTOPP_8_6_0.tar.gz : 9304625f4767a13e0a5f26d0f019d78cf9375604a33e5391c3bf2e81399dfeb8
license    : BSL-1.0
component  : programming
summary    : Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
description: |
    Crypto++ Library is a free C++ class library of cryptographic algorithms and schemes
build      : |
    %make dynamic libcryptopp.pc
install    : |
    %make_install PREFIX=/usr

    # Remove unused test data
    rm -rf $installdir/usr/share $installdir/usr/bin
